nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org/"
packageExtensions:
  "@redofy-accounting/website@*":
    peerDependencies:
      "vue": "*"
enableGlobalCache: true
checksumBehavior: update
networkConcurrency: 8
nmMode: hardlinks-local
compressionLevel: 0
nmHoistingLimits: workspaces 