nodeLinker: node-modules

enableGlobalCache: true

checksumBehavior: update

npmRegistryServer: "https://registry.npmjs.org/"

# Removing the yarnPath that doesn't exist
# yarnPath: ".yarn/releases/yarn-4.9.1.cjs"

packageExtensions:
  "@redofy-accounting/website@*":
    peerDependencies:
      vue: "*"
  "@redofy-accounting/dashboard@*":
    peerDependencies:
      vue: "*"

# Make sure we're using workspaces correctly
networkConcurrency: 8
nmMode: hardlinks-local
compressionLevel: 0
nmHoistingLimits: workspaces 