version: '3'
services:
  directus:
    image: directus/directus:10.7
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9c3f-2c7d8f6e4ac1'
      SECRET: '2d8c98e1-4e91-40b7-94e4-d7ac11c82103'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      ADMIN_EMAIL: 'admin@redofy.se'
      ADMIN_PASSWORD: 'RedofyAdmin123!'
      PUBLIC_URL: 'http://localhost:8055'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'http://localhost:3000,http://localhost:3001'
      RATE_LIMITER_ENABLED: 'false'
      CACHE_ENABLED: 'false'
      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_DRIVER: 'local'
      STORAGE_LOCAL_ROOT: './uploads'

  database:
    image: postgres:15
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  # Optional adminer for database management through web interface
  adminer:
    image: adminer
    restart: always
    ports:
      - "8056:8080"
    depends_on:
      - database 