// generated by unplugin-vue-components
// We need this file for Nuxt 3 + TypeScript to recognize global components
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    // Add global component types here if needed
  }
}

export {} 